name: fatura_yeni
description: "Akıllı fatura tanıma ve yönetim uygulaması."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.5.1 
  
  # API İstekleri
  http: ^1.2.1
  flutter_dotenv: ^5.1.0
  
  # Vektörel İkonlar
  flutter_svg: ^2.0.10+1
  
  # Özel Fontlar
  google_fonts: ^6.2.1
  
  # iOS Stili İkonlar
  cupertino_icons: ^1.0.6
  
  # Çoklu Dil Desteği (i18n)
  flutter_localizations:
    sdk: flutter
  intl: 0.20.2

  # Özel UI Bileşenleri
  intl_phone_field: ^3.2.0
  pinput: ^5.0.2

  # Firebase Entegrasyonu
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  firebase_app_check: ^0.4.0+1
  firebase_storage: ^13.0.1
  cloud_firestore: ^6.0.1
  
  # Theme Management
  shared_preferences: ^2.2.2
  provider: ^6.1.1

  # Güvenli Depolama
  flutter_secure_storage: ^9.2.2

  # Kamera ve Dosya Seçimi
  camera: ^0.11.0+1
  file_picker: ^10.3.2
  image_picker: ^1.1.2

  # WebSocket Bağlantısı
  web_socket_channel: ^3.0.3
  
  # Excel ve CSV Export
  excel: ^4.0.6
  path_provider: ^2.1.2
  permission_handler: ^12.0.1
  
  # Cihaz Bilgileri
  device_info_plus: ^11.5.0
  
  # Dosya Açma
  open_file: ^3.5.10
  syncfusion_flutter_pdfviewer: ^30.2.7
  dotted_border: ^3.1.0
  flutter_dropzone: ^4.2.1
  cunning_document_scanner: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^6.0.0

# Flutter'a özel yapılandırmalar bu tek bölüm altında toplanmalıdır.
flutter:
  uses-material-design: true
  generate: true # Çoklu dil desteği için kod üretimi

  # Uygulama varlıkları (resim, json vb.)
  assets:
    - assets/
    - .env